# Generated by Django 3.2.8 on 2021-10-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=128, unique=True, verbose_name='title')),
                ('category', models.CharField(choices=[('음주운전', '음주운전'), ('공무집행방해', '공무집행방해'), ('도주치사상(뺑소니)', '도주치사상(뺑소니)'), ('사기죄', '사기죄'), ('명예훼손', '명예훼손'), ('모욕죄', '모욕죄'), ('공연음란죄', '공연음란죄'), ('강제추행', '강제추행'), ('강간', '강간'), ('뇌물', '뇌물'), ('보이스피싱', '보이스피싱'), ('카촬', '카촬'), ('주거침입', '주거침입'), ('통매음', '통매음'), ('교통범죄(신호위반 등) (교통특례법)', '교통범죄(신호위반 등) (교통특례법)'), ('폭행, 상해 등 폭력범죄', '폭행, 상해 등 폭력범죄'), ('마약', '마약'), ('도박', '도박'), ('강도', '강도'), ('업무방해', '업무방해'), ('협박', '협박'), ('운전자폭행', '운전자폭행'), ('성매매', '성매매'), ('아청법', '아청법'), ('음주측정거부', '음주측정거부'), ('절도', '절도'), ('성범죄 전반', '성범죄 전반'), ('코로나방역수칙위반(감염병예방법)', '코로나방역수칙위반(감염병예방법)'), ('재물손괴', '재물손괴'), ('아동학대', '아동학대'), ('횡령, 배임', '횡령, 배임')], max_length=128, verbose_name='분류')),
                ('cert', models.BooleanField(default=False, verbose_name='수료여부')),
                ('score', models.IntegerField(null=True, verbose_name='점수')),
                ('user', models.CharField(max_length=128, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'QuizContents',
                'verbose_name_plural': 'QuizContents',
                'db_table': 'QuizContents',
                'ordering': ['quiz_title'],
            },
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['category'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer5',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='ans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('음주운전', '음주운전'), ('공무집행방해', '공무집행방해'), ('도주치사상(뺑소니)', '도주치사상(뺑소니)'), ('사기죄', '사기죄'), ('명예훼손', '명예훼손'), ('모욕죄', '모욕죄'), ('공연음란죄', '공연음란죄'), ('강제추행', '강제추행'), ('강간', '강간'), ('뇌물', '뇌물'), ('보이스피싱', '보이스피싱'), ('카촬', '카촬'), ('주거침입', '주거침입'), ('통매음', '통매음'), ('교통범죄(신호위반 등) (교통특례법)', '교통범죄(신호위반 등) (교통특례법)'), ('폭행, 상해 등 폭력범죄', '폭행, 상해 등 폭력범죄'), ('마약', '마약'), ('도박', '도박'), ('강도', '강도'), ('업무방해', '업무방해'), ('협박', '협박'), ('운전자폭행', '운전자폭행'), ('성매매', '성매매'), ('아청법', '아청법'), ('음주측정거부', '음주측정거부'), ('절도', '절도'), ('성범죄 전반', '성범죄 전반'), ('코로나방역수칙위반(감염병예방법)', '코로나방역수칙위반(감염병예방법)'), ('재물손괴', '재물손괴'), ('아동학대', '아동학대'), ('횡령, 배임', '횡령, 배임')], max_length=128, null=True, verbose_name='분류'),
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='Quiz',
        ),
    ]
