# Generated by Django 3.2.8 on 2021-10-20 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_auto_20211020_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcontents',
            name='score',
            field=models.IntegerField(default=0, null=True, verbose_name='점수'),
        ),
        migrations.AlterField(
            model_name='quizcontents',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='구매자'),
        ),
    ]
